#! /usr/bin/env bash

tsc -p tsconfig.json

cp package.json dist

json -f package.json -e "delete this.devDependencies; delete this.scripts;" > dist/package.json
json -f package.json -e "this.types = 'index.d.ts';" > dist/package.json
